language: general

branches:
  only:
  - master

env:
  - REPO_PREFIX=homebrew-appimage
  - REPO_PREFIX=homebrew-athruncask
  - REPO_PREFIX=homebrew-genericbinary
  - REPO_PREFIX=homebrew-linuxbinary
  - REPO_PREFIX=homebrew-osxbinary

script:
  - git -c user.name='travis' -c user.email='travis' push "https://athrunsun:${GITHUB_API_TOKEN}@github.com/athrunsun/$REPO_PREFIX.git" `git subtree split --prefix $REPO_PREFIX master`:master -f &> /dev/null
